# Generated by Django 6.0.4 on 2026-08-20 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0003_shoppulsesignal_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdashboardsnapshot',
            name='today_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdashboardsnapshot',
            name='today_gross_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='shopdashboardsnapshot',
            name='today_sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoplowstocksnapshot',
            name='stock_on_hand',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
    ]
