# Generated by Django 6.0.4 on 2026-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_registersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='restock_goods',
            field=models.BooleanField(default=True),
        ),
    ]
