# Generated by Django 6.0.4 on 2026-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salereturn_restock_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='eway_bill_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sale',
            name='lr_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
