# Generated by Django 6.0.4 on 2026-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktake_stocktakeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
