# Generated by Django 6.0.4 on 2026-09-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_unique_sku_per_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='attributes_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
