# Generated by Django 6.0.4 on 2026-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryitem_attributes_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystockledger',
            name='unit_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
