# Generated by Django 6.0.4 on 2026-08-22 05:30

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customerstatementlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='home_address',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, default='')),
        ),
        migrations.AddField(
            model_name='customer',
            name='work_address',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, default='')),
        ),
    ]
