# Generated by Django 6.0.4 on 2026-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_home_address_customer_work_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_terms_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
