# Generated by Django 6.0.4 on 2026-08-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpasskeycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='token_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
