# Generated by Django 6.0.4 on 2026-08-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_shopmembership_pos_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='brand_color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo_data',
            field=models.TextField(blank=True),
        ),
    ]
