# Generated by Django 6.0.4 on 2026-08-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('products', 'Products'), ('customers', 'Customers'), ('sales', 'Past sales')], max_length=16),
        ),
    ]
